version: "3.9"

services:
  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_PASSWORD=123456
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default:
